'directory': 'bert'
'log_directory': '/data/run01/scw6doz/lzx_out/vpipe/output'
'module': 'vgpus=4'
'data_dir': '/data/run01/scw6doz/lzx/vpipe/bert_pretrain_wikicorpus_tokenized_hdf5_seqlen128'
'config_file': 'vgpus=4/mp_conf.json'
'partition': 'vgpus=4/vpipe.json'
'container': '/data/run01/scw6doz/lzx/vpipe/vpipe.sif'
'machines': ['localhost:0', 'localhost:1', 'localhost:2', 'localhost:3']
'sync_mode': 'asp'
'batch_size': 16
'learning_rate': 0.03
'weight_decay': 0.000
'epochs': 2
'print_frequency': 100
'verbose_frequency': 0
'compress_activations': False
'compress_in_gpu': False
'learning_rate_policy': 'polynomial'
'model_type': 'bert'
'distributed_backend': 'gloo'
